name: Announce Update to Discord

on:
  push:
    branches:
      - main
      - dev

jobs:
  announce:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Announce to Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": "New Update Pushed to Repository!",
                "description": "A new update has been pushed to the **Park Manager: Beyond The Gates** repository.",
                "url": "https://github.com/aresvrcofficial/park-manager-beyond-the-gates/commit/${{ github.sha }}",
                "color": 3066993,
                "author": {
                  "name": "GitHub Actions",
                  "icon_url": "https://github.githubassets.com/images/modules/logos_page/Octocat.png"
                },
                "fields": [
                  {
                    "name": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}"
                  },
                  {
                    "name": "Author",
                    "value": "${{ github.event.head_commit.author.name }}"
                  }
                ],
                "timestamp": "${{ github.event.head_commit.timestamp }}"
              }]
            }' \
        $DISCORD_WEBHOOK
